2016-02-06 12:11:35,262 - tornado.application - ERROR - Uncaught exception GET /index (::1)
HTTPServerRequest(protocol='http', host='localhost:888', method='GET', uri='/index', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'zh-CN,zh;q=0.8', 'Accept-Encoding': 'gzip,deflate,sdch', 'Host': 'localhost:888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0'})
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\tornado-4.3-py2.7-win32.egg\tornado\web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "F:\Solution\now\Solutions\ServerSolution\ArmyAppServer\core\handlers\index.py", line 16, in get
    accesss_log.info('test indexhandler logger')
NameError: global name 'accesss_log' is not defined
2016-02-06 12:11:35,263 - tornado.access - ERROR - 500 GET /index (::1) 3.00ms
